import { Project, UIElement, AnimationKeyframe } from '../types';

export function generateLuaCode(project: Project): string {
  let code = `-- Generated by dalley.
-- High-Fidelity Roblox UI Animation Script

local Players = game:GetService("Players")
local RunService = game:GetService("RunService")

-- Injecting SPR Library via URL (Standard Dalley Logic)
local SPR = loadstring(game:HttpGet("https://raw.githubusercontent.com/Fraktality/spr/master/spr.lua"))()

local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")

local screenGui = Instance.new("ScreenGui")
screenGui.Name = "${project.name.replace(/\s+/g, '')}"
screenGui.IgnoreGuiInset = true
screenGui.ResetOnSpawn = false
screenGui.Parent = playerGui

local elements = {}
`;

  // Create UI Instances
  project.elements.forEach(el => {
    const varName = `el_${el.id.replace(/-/g, '_')}`;
    code += `\n-- element: ${el.name}\nlocal ${varName} = Instance.new("${el.type}")\n`;
    code += `${varName}.Name = "${el.name}"\n`;
    
    const p = el.properties;
    code += `${varName}.Position = UDim2.new(${p.Position.X.Scale}, ${p.Position.X.Offset}, ${p.Position.Y.Scale}, ${p.Position.Y.Offset})\n`;
    code += `${varName}.Size = UDim2.new(${p.Size.X.Scale}, ${p.Size.X.Offset}, ${p.Size.Y.Scale}, ${p.Size.Y.Offset})\n`;
    code += `${varName}.BackgroundColor3 = Color3.new(${p.BackgroundColor3.R}, ${p.BackgroundColor3.G}, ${p.BackgroundColor3.B})\n`;
    code += `${varName}.BackgroundTransparency = ${p.BackgroundTransparency}\n`;
    code += `${varName}.BorderSizePixel = ${p.BorderSizePixel}\n`;
    code += `${varName}.Visible = ${p.Visible}\n`;
    code += `${varName}.ZIndex = ${p.ZIndex}\n`;
    code += `${varName}.AnchorPoint = Vector2.new(${p.AnchorPoint.X}, ${p.AnchorPoint.Y})\n`;
    code += `${varName}.Rotation = ${p.Rotation}\n`;

    if (p.Text !== undefined) {
      code += `${varName}.Text = [[${p.Text}]]\n`;
      if (p.TextColor3) code += `${varName}.TextColor3 = Color3.new(${p.TextColor3.R}, ${p.TextColor3.G}, ${p.TextColor3.B})\n`;
      if (p.TextSize) code += `${varName}.TextSize = ${p.TextSize}\n`;
    }
    
    if (p.Image) code += `${varName}.Image = "${p.Image}"\n`;

    if (p.UICorner) {
      code += `local corner_${varName} = Instance.new("UICorner", ${varName})\n`;
      code += `corner_${varName}.CornerRadius = UDim.new(${p.UICorner.CornerRadius.Scale}, ${p.UICorner.CornerRadius.Offset})\n`;
    }

    if (p.UIStroke) {
      code += `local stroke_${varName} = Instance.new("UIStroke", ${varName})\n`;
      code += `stroke_${varName}.Thickness = ${p.UIStroke.Thickness}\n`;
      code += `stroke_${varName}.Color = Color3.new(${p.UIStroke.Color.R}, ${p.UIStroke.Color.G}, ${p.UIStroke.Color.B})\n`;
      code += `stroke_${varName}.Transparency = ${p.UIStroke.Transparency}\n`;
    }

    code += `elements["${el.id}"] = ${varName}\n`;
  });

  // Hierarchy
  project.elements.forEach(el => {
    const varName = `el_${el.id.replace(/-/g, '_')}`;
    if (el.parent && el.parent !== 'root') {
      const parentVar = `el_${el.parent.replace(/-/g, '_')}`;
      code += `${varName}.Parent = ${parentVar}\n`;
    } else {
      code += `${varName}.Parent = screenGui\n`;
    }
  });

  // Animation Engine (SPR Implementation)
  if (project.animations.length > 0) {
    code += `\n-- Animation Logic\nlocal function runAnimations()\n`;
    const animationsByElement = project.animations.reduce((acc, anim) => {
      if (!acc[anim.elementId]) acc[anim.elementId] = [];
      acc[anim.elementId].push(anim);
      return acc;
    }, {} as Record<string, AnimationKeyframe[]>);

    Object.entries(animationsByElement).forEach(([elId, kfs]) => {
      const varName = `el_${elId.replace(/-/g, '_')}`;
      kfs.sort((a, b) => a.time - b.time).forEach((kf, idx) => {
        const delay = idx === 0 ? kf.time : kf.time - kfs[idx-1].time;
        if (delay > 0) code += `  task.wait(${delay})\n`;
        
        const props = Object.entries(kf.properties).map(([key, val]) => {
            if (key === 'Position') return `Position = UDim2.new(${val.X.Scale}, ${val.X.Offset}, ${val.Y.Scale}, ${val.Y.Offset})`;
            if (key === 'Size') return `Size = UDim2.new(${val.X.Scale}, ${val.X.Offset}, ${val.Y.Scale}, ${val.Y.Offset})`;
            if (key === 'BackgroundColor3') return `BackgroundColor3 = Color3.new(${val.R}, ${val.G}, ${val.B})`;
            return `${key} = ${typeof val === 'string' ? '"' + val + '"' : val}`;
        }).join(", ");

        code += `  SPR.target(${varName}, ${kf.sprSettings.dampingRatio}, ${kf.sprSettings.undampedFrequency}, {${props}})\n`;
      });
    });
    code += `end\n\ntask.spawn(runAnimations)\n`;
  }

  code += `\nprint("dalley: Interface synced and running.")\n`;
  return code;
}
